#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_add_swap
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi
ynh_config_remove_systemd"$app-web"

if ynh_hide_warnings yunohost service status "$app-sidekiq" >/dev/null; then
    yunohost service remove "$app-sidekiq"
fi
ynh_config_remove_systemd"$app-sidekiq"

ynh_config_remove_nginx

#=================================================
# REMOVE VARIOUS FILES
#=================================================

ynh_safe_rm "/etc/$app"

#REMOVEME? (Apps should not remove their log dir during remove ... this should only happen if --purge is used, and be handled by the core...) ynh_safe_rm "/var/log/$app"

ynh_script_progression "Removing Swap..."
ynh_del_swap

ynh_script_progression "Uninstalling Ruby..."
ynh_ruby_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
